Admin client aggregator features
aktin/broker pull request #37
Opened 2023-07-13 07:56 UTC by akomii

Added features of Broker aggregator (create UUID and download aggregated Results) to AdminClient

2023-08-04 13:59 UTC, rwm requested changes

2023-08-04 13:59 UTC, rwm commented on broker-client/src/main/java/org/aktin/broker/client2/BrokerAdmin2.java
> +    public String getAggregatedResultUUID(int requestId) throws IOException {
Dass hier eine UUID verwendet wird, ist irrelevant für die API. Dieses Implementierungsdetail sollte nicht nach außen kommuniziert werden. Intern könnte das nämlich geändert werden ohne dass es für den Nutzer relevant ist. Besser einfach "Id" nennen.

2023-08-04 13:59 UTC, rwm commented on broker-client/src/main/java/org/aktin/broker/client2/BrokerAdmin2.java
> +    public String getAggregatedResultUUID(int requestId) throws IOException {
AggregatedResult finde ich nicht so passend. Es ist ja nicht mehr unbedingt 1 Result und Aggregiert wird genaugenommen nichts. Eher richtung export bundle, ähnlich wie es im REST call heißt.. bin aber auch offen für Diskussion und Argumente warum anders..

2023-08-04 13:59 UTC, rwm commented on broker-client/src/main/java/org/aktin/broker/client2/BrokerAdmin2.java
> +    public ResponseWithMetadata getAggregatedResult(String uuid) throws IOException {
Gibt es einen Grund warum das in zwei Calls aufgeteilt sein muss? (get..ID und get..Result) Aus Nutzersicht würde es ja reichen einen Call zu haben, solange dieser Asynchron ausgeführt werden kann. Auf Serverseite ist das unterschiedlich, weil 1. beim Browserdownload (damals) keine Authentifizerungsinformationen mitgeschickt werden konnte und 2. die Erzeugung der Zipdatei länger dauern könnte (asynchron).

2023-10-04 10:05 UTC, akomii commented on broker-client/src/main/java/org/aktin/broker/client2/BrokerAdmin2.java
> +    public String getAggregatedResultUUID(int requestId) throws IOException {
geeinigt auf `getRequestBundleExport()`

2024-10-01 12:35 UTC, rwm approved these changes

2024-10-01 12:35 UTC, merged